server {
    listen 80;
    listen [::]:80;
    server_name _;

    add_header Cross-Origin-Opener-Policy 'same-origin' always;
    add_header Cross-Origin-Embedder-Policy 'require-corp' always;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/index.html $uri.html /index.html;
    }

    location /_app/immutable/ {
      root /usr/share/nginx/html;
      expires 1y;
      add_header Cache-Control "public, immutable";
    }
}